version: "3.6"

services:
  splunk:
    image: splunk/splunk:latest
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Password1234
      - SPLUNK_LICENSE_URI=Free
      - SPLUNK_HEC_TOKEN=abcd1234
    ports:
      - 8000:8000
      - 8088:8088
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.2
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elksplunklogger:9200
      ELASTICSEARCH_HOSTS: '["http://elksplunklogger:9200"]'
    ports:
      - "5601:5601"
  elksplunklogger:
    build: .
